# Generated by Django 4.2.10 on 2026-03-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_question_difficulty_alter_question_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.CharField(blank=True, help_text='e.g. Grade 10, Undergraduate Year 2', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('easy_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('hard_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('visibility', models.CharField(choices=[('private', 'Private (invite only)'), ('public', 'Public (anyone can join)')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('answers_released', models.BooleanField(default=False, help_text='When True, students see correct answers + explanations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_test', to='quizzes.quiz')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('invalidated', 'Invalidated')], default='not_started', max_length=15)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Actual seconds from start to submit', null=True)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('suspicious_activity', models.BooleanField(default=False)),
                ('invalidation_reason', models.CharField(blank=True, max_length=255)),
                ('current_question_order', models.PositiveIntegerField(default=1)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Rank within this test, computed after all submissions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-score', 'time_taken_seconds'],
            },
        ),
        migrations.CreateModel(
            name='TestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_type', models.CharField(choices=[('assigned', 'Assigned by Teacher'), ('self', 'Self Enrolled')], default='assigned', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='Teacher who assigned this, null if self-enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_enrollments', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tests_app.test')),
            ],
            options={
                'db_table': 'test_enrollments',
            },
        ),
        migrations.CreateModel(
            name='TestAttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests_app.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to='quizzes.question')),
            ],
            options={
                'db_table': 'test_attempt_answers',
            },
        ),
        migrations.AddField(
            model_name='testattempt',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='tests_app.testenrollment'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests_app.test'),
        ),
        migrations.CreateModel(
            name='TestAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('submitted_count', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('lowest_score', models.FloatField(default=100.0)),
                ('score_std_dev', models.FloatField(default=0.0)),
                ('easy_accuracy', models.FloatField(default=0.0)),
                ('medium_accuracy', models.FloatField(default=0.0)),
                ('hard_accuracy', models.FloatField(default=0.0)),
                ('score_distribution', models.JSONField(default=dict)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tests_app.test')),
            ],
            options={
                'db_table': 'test_analytics',
            },
        ),
        migrations.AddIndex(
            model_name='testenrollment',
            index=models.Index(fields=['test', 'student'], name='test_enroll_test_id_d9ffcf_idx'),
        ),
        migrations.AddIndex(
            model_name='testenrollment',
            index=models.Index(fields=['student'], name='test_enroll_student_56ed93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testenrollment',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='testattemptanswer',
            index=models.Index(fields=['attempt'], name='test_attemp_attempt_b93baa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status'], name='test_attemp_test_id_3e23fc_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'score'], name='test_attemp_test_id_ccd700_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student'], name='test_attemp_student_bd7726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['teacher'], name='tests_teacher_6c3e27_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='tests_status_7b792f_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['start_time', 'end_time'], name='tests_start_t_35ad94_idx'),
        ),
    ]
