# Generated by Django 4.2.10 on 2026-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('quiz_created', 'Quiz Created'), ('quiz_started', 'Quiz Started'), ('answer_submitted', 'Answer Submitted'), ('quiz_completed', 'Quiz Completed'), ('attempt_invalidated', 'Attempt Invalidated'), ('admin_created_user', 'Admin Created User'), ('admin_deleted_user', 'Admin Deleted User'), ('admin_deleted_quiz', 'Admin Deleted Quiz'), ('teacher_approved', 'Teacher Approved'), ('test_created', 'Test Created'), ('test_assigned', 'Test Assigned'), ('test_started', 'Test Started'), ('test_submitted', 'Test Submitted'), ('answers_released', 'Answers Released'), ('test_deleted', 'Test Deleted')], db_index=True, max_length=50),
        ),
    ]
