# Generated by Django 4.2.10 on 2026-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Set for TEST mode', null=True),
        ),
    ]
